# User Preferences Extra Configuration

# Language Settings
language:
  default: en
  options:
    - en
    - es
    - fr
    - zh

# Currency Settings
currency:
  default: USD
  options:
    - USD
    - EUR
    - GBP
    - JPY

# Theme Settings
theme:
  default: light
  options:
    - light
    - dark
    - galaxy

# Notification Settings
notifications:
  enabled: true
  frequency:
    - daily
    - weekly
    - monthly

# Galactic Vault Settings
galactic_vault:
  default_folder: MyGalaxy
  show_hidden_files: false

# AI Assistant Settings
ai_assistant:
  enabled: true
  personality:
    - friendly
    - professional
    - humorous
